CREATE TYPE "SavingType" AS ENUM (
  'PRICE_REDUCTION',
  'SUPPLIER_SWITCH',
  'REBATE_CREDIT',
  'SPECIFICATION_CHANGE',
  'VOLUME_CONSOLIDATION',
  'FREIGHT_LOGISTICS',
  'PAYMENT_TERMS',
  'PROCESS_TOLLING',
  'COST_AVOIDANCE',
  'OTHER'
);

CREATE TYPE "SavingsImpactType" AS ENUM (
  'HARD_SAVINGS',
  'COST_AVOIDANCE',
  'CASH_FLOW_IMPROVEMENT',
  'WORKING_CAPITAL_IMPACT',
  'RISK_CONTINUITY_BENEFIT'
);

CREATE TYPE "SavingsImpactRecurrence" AS ENUM (
  'RECURRING',
  'ONE_TIME',
  'TEMPORARY',
  'UNKNOWN'
);

CREATE TYPE "SavingsBudgetImpact" AS ENUM (
  'BUDGET_IMPACT',
  'FORECAST_AVOIDANCE',
  'NON_BUDGET_OPERATIONAL_BENEFIT',
  'UNKNOWN'
);

ALTER TABLE "SavingCard" RENAME COLUMN "savingType" TO "legacySavingsMethod";
ALTER TABLE "SavingCard" ALTER COLUMN "legacySavingsMethod" DROP NOT NULL;

ALTER TABLE "SavingCard"
  ADD COLUMN "savingType" "SavingType" NOT NULL DEFAULT 'PRICE_REDUCTION',
  ADD COLUMN "impactType" "SavingsImpactType" NOT NULL DEFAULT 'HARD_SAVINGS',
  ADD COLUMN "impactRecurrence" "SavingsImpactRecurrence" NOT NULL DEFAULT 'RECURRING',
  ADD COLUMN "budgetImpact" "SavingsBudgetImpact" NOT NULL DEFAULT 'BUDGET_IMPACT';
