CREATE TYPE "EvidenceType" AS ENUM (
  'SUPPLIER_QUOTE',
  'PRICE_CONFIRMATION',
  'CONTRACT_OR_PO',
  'INVOICE_OR_ACTUAL',
  'CALCULATION_WORKBOOK',
  'TECHNICAL_APPROVAL',
  'CUSTOMER_APPROVAL',
  'REBATE_AGREEMENT',
  'TOLLING_RATE_CARD',
  'NEGOTIATION_SUMMARY',
  'OTHER'
);

ALTER TABLE "SavingCardEvidence"
  ADD COLUMN "evidenceType" "EvidenceType" NOT NULL DEFAULT 'OTHER',
  ADD COLUMN "sourceDate" TIMESTAMP(3),
  ADD COLUMN "notes" TEXT;
